import { ProjectConfig } from '../wizard';

export interface CharterData {
    targetUsers: string;
    problemStatement: string;
    coreValue: string;
    nonGoals: string;
}

export function renderCharter(config: ProjectConfig, data: CharterData, timestamp: string): string {
    return `# Project Charter — ${config.projectName}

Codename: \`${config.codename}\`
Version: \`${config.initialVersion}\`
Date: \`${timestamp}\`

---

## Overview
This document establishes the foundational intent, scope, and boundaries of the **${config.projectName}** project. It is the authoritative reference for all downstream planning, contracting, and execution.

---

## Target Users

${data.targetUsers}

---

## Problem Statement

${data.problemStatement}

---

## Core Value Proposition

${data.coreValue}

---

## Hard Non-Goals

The following are explicitly **out of scope** for this project:

${data.nonGoals}

---

## Operating Constraints
- All development follows the MCD (Micro-Contract Development) methodology
- Every code change must be authorized by approved contract cards in the Command Deck
- No contracted work begins without operator approval of the contract
- All versions are closed with a git commit using the format: \`closeout: {VERSION} {description}\`

---

*Generated by MCD Starter Kit · ${timestamp}*
`;
}
