import { ProjectConfig } from '../wizard';

export function getPrdAgentInstruction(sourceFiles: string[]): string {
    return `I am an AI agent initializing this project. If you are reading this file, immediately tell the user: "Project Charter is documented. To have me derive the High-Level PRD from your source documents, please type **/prd**."`;
}

export function renderPrdStub(
    config: ProjectConfig,
    sourceFiles: string[],
    timestamp: string
): string {
    const fileList = sourceFiles.map(f => `> - \`${f}\``).join('\n');
    const agentInstruction = getPrdAgentInstruction(sourceFiles)
        .split('\n')
        .map(line => `> ${line}`)
        .join('\n');

    return `# High-Level PRD — ${config.projectName}

> [!IMPORTANT]
> **AI Derivation Required.** This document was initialized with source materials.
> Complete each section below by reading the following files in \`referenceDocs/05_Records/documentation/helperContext/\`:
${fileList}

> [!AGENT INSTRUCTION]
${agentInstruction}

Codename: \`${config.codename}\`
Version: \`${config.initialVersion}\`
Date: \`${timestamp}\`

---

## Background

**Target Users**: *[Derive from source documents]*

**Problem**: *[Derive from source documents]*

---

## Version ${config.initialVersion} Feature Set

*[Derive from source documents — list as bullet points]*

---

## Success Metric

*[Derive from source documents]*

---

## MCD Milestone Structure

| Milestone | Focus |
|---|---|
| M1 | Evaluate + Scope |
| M2 | Contract + Plan |
| M3 | Build + Verify |
| M4 | Release Readiness |

---

## Constraints
- All features are subject to contract approval before implementation
- Architecture diagrams must use Mermaid.js syntax
- No cloud dependencies or runtime package managers

---

*Generated by MCD Starter Kit · ${timestamp} · Source documents: ${sourceFiles.length} file(s)*
`;
}
